spring:
  application:
    name: demo
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/testyj
    username: root
    password: 1234
  devtools:
    livereload:
      enabled: true 

server:
  port: 8080

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    jsp:
      init-parameters:
        development: true
  error:
    whitelabel:
      enabled: false

mybatis:
  type-aliases-package: com.example.demo.domain
  mapper-locations: mapper/**/*.xml

logging:
  config: classpath:logback-spring.xml